Reading big data (~1gb file using bcftools to filter for ERAP2 genomic positions, to remove metadata header and after processing file in Ubuntu, converting to tabular CSV format retaining essential variant information for downstream haplotype assembling, statistical analysis and visualization in Python. 
**A tab-delimited variant file (ERAP2_mod.csv) was read in 20,000-row chunks using pandas (v2.1.4) in Python3. Chunks were concatenated into a single DataFrame to enable memory-efficient processing.**

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
mylist=[]
for chunk in pd.read_csv('/hpc/dla_lti/araja/hapsnew/ERAP2homedir/ERAP2_mod.csv', chunksize=20000, sep="\t"):
    mylist.append(chunk)
big_dataERAP2=pd.concat(mylist, axis=0)
del mylist

In [2]:
big_dataERAP2

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,4132678,...,2481674,2247529,2513225,5310978,3340022,2278245,2686110,1085546,3156158,4198099
0,5,96762462,.,T,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1,5,96765121,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
2,5,96765128,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
3,5,96765133,.,C,T,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
4,5,96765137,.,C,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1491,5,96917665,.,G,C,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1492,5,96917682,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1493,5,96917688,.,C,T,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1494,5,96917689,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1495,5,96917703,.,G,C,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0

##**Removing duplicated data if any**##

In [3]:
big_dataERAP2[big_dataERAP2.duplicated(keep=False)]
big_dataERAP2

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,4132678,...,2481674,2247529,2513225,5310978,3340022,2278245,2686110,1085546,3156158,4198099
0,5,96762462,.,T,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1,5,96765121,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
2,5,96765128,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
3,5,96765133,.,C,T,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
4,5,96765137,.,C,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1491,5,96917665,.,G,C,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1492,5,96917682,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1493,5,96917688,.,C,T,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1494,5,96917689,.,G,A,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
1495,5,96917703,.,G,C,.,PASS,.,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0

In [4]:
##Removing the columns that are not required
big_dataERAP2.pop('QUAL')
big_dataERAP2.pop('FILTER')
big_dataERAP2.pop('INFO')
big_dataERAP2.pop('#CHROM')
big_dataERAP2.pop('FORMAT')
big_dataERAP2.pop('ID')

0       .
1       .
2       .
3       .
4       .
       ..
1491    .
1492    .
1493    .
1494    .
1495    .
Name: ID, Length: 1496, dtype: object

**Reading frequency of variants file calculated using PLINK 2.0**
plink2 --vcf ERAP2.vcf --freq --out Plink_ERAP2awk '{print $1, $5}' Plink_ERAP2.afreq > Plink_ERAP2.csv

In [5]:
ERAP2_PLINK=pd.read_csv('/hpc/dla_lti/araja/haplotypes/Plink_ERAP2.csv')
ERAP2_PLINK

           POS  Allele_Freq
0     96762462     0.000608
1     96765121     0.000006
2     96765128     0.000006
3     96765133     0.000009
4     96765137     0.000015
...        ...          ...
1491  96917665     0.000006
1492  96917682     0.000021
1493  96917688     0.000015
1494  96917689     0.000006
1495  96917703     0.000018

[1496 rows x 2 columns]

In [6]:
###Add frequency data to ERAP2 genotype file####
#based on POS common column#
df1n = big_dataERAP2.set_index('POS')
df2n = ERAP2_PLINK.set_index('POS')
ERAP2AlleleFreqPlinkMerge=df1n.merge(df2n, how='left', on='POS')
ERAP2AlleleFreqPlinkMerge

,REF,ALT,4132678,3856798,1684021,2365580,4866862,5133998,1364128,3063435,...,2247529,2513225,5310978,3340022,2278245,2686110,1085546,3156158,4198099,Allele_Freq
POS,,,,,,,,,,,,,,,,,,,,,
96762462,T,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000608
96765121,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000006
96765128,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000006
96765133,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000009
96765137,C,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96917665,G,C,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000006
96917682,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000021
96917688,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000015
96917689,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000006
96917703,G,C,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0.000018

**Downloaded GnomAD file for ERAP2 variants, filtered it for variants of interest and using allele_frequency reported for European population and finally saved in  ERAP2_var_GnomAD**

In [7]:
ERAP2_gnomeAD=pd.read_csv('/hpc/dla_lti/araja/haplotypes/ERAP2_var_GnomAD.csv')
ERAP2_gnomeAD

,POS,rsIDs,Reference,Alternate,Protein_Consequence,VEP_Annotation,Allele Frequency
0,96879799,rs144285538,C,G,p.Phe38Leu,missense_variant,0.000460
1,96879921,rs775400779,A,T,p.Asp79Val,missense_variant,0.000125
2,96880025,rs149963216,G,A,p.Asp114Asn,missense_variant,0.000125
3,96880025,rs149963216,G,T,p.Asp114Tyr,missense_variant,0.001406
4,96880043,rs145045143,G,C,p.Ala120Pro,missense_variant,0.001629
5,96883830,rs73150323,G,A,p.Arg205His,missense_variant,0.000256
6,96883857,rs3733905,C,T,p.Pro214Leu,missense_variant,0.009415
7,96886656,rs80193285,T,C,p.Val239Ala,missense_variant,0.005473
8,96889200,rs117041256,T,G,p.Ser289Ala,missense_variant,0.010494
9,96889219,rs113033185,A,T,p.Gln295Leu,missense_variant,0.000250
10,96889330,rs201327810,T,C,p.Val332Ala,missense_variant,0.000118
11,96892359,rs762260525,A,G,p.Tyr344Cys,missense_variant,0.000164
12,96892368,rs75263594,C,T,p.Thr347Met,missense_variant,0.021268
13,96895296,rs2549782,G,T,p.Lys392Asn,missense_variant,0.541584
14,96895313,rs144292939,A,G,p.Tyr398Cys,missense_variant,0.000105
15,96895339,rs138646616,A,G,p.Thr407Ala,missense_variant,0.000118
16,96895352,rs34261036,T,G,p.Leu411Arg,missense_variant,0.003390
17,96895360,rs375167935,G,C,NaN,splice_donor_variant,0.000184
18,96896395,rs148344927,G,A,p.Cys421Tyr,missense_variant,0.000526
19,96896494,rs147381806,C,T,p.Ser454Phe,missense_variant,0.000197
20,96896817,rs201986447,G,A,p.Ser486Asn,missense_variant,0.000217
21,96896829,rs376575375,C,A,p.Ala490Asp,missense_variant,0.000138
22,96896833,rs773050594,G,T,p.Lys491Asn,missense_variant,0.000117
23,96896864,NaN,G,GTAAGTCATATGTTGGGTAACGATAGACTGTTATTTAATCTAGAAA...,NaN,splice_donor_variant,0.002777
24,96896864,rs1581849348,G,GTAAGTCATATGTTGGGTAACGATAGACTGTTATTTAATCTAGAAA...,NaN,splice_donor_variant,0.223619
25,96900192,rs2248374,A,G,NaN,splice_region_variant,0.541775
26,96901626,rs151035607,C,T,p.Arg565Cys,missense_variant,0.000296
27,96902287,rs139804478,A,T,p.Ile588Phe,missense_variant,0.000237
28,96903449,rs145822095,A,G,p.His634Arg,missense_variant,0.000716
29,96903530,rs61731306,G,T,p.Gly661Val,missense_variant,0.005824
30,96903554,rs17408150,T,A,p.Leu669Gln,missense_variant,0.038022
31,96908993,rs200317861,A,T,p.Asp682Val,missense_variant,0.000118
32,96909101,rs373745801,T,C,p.Ile718Thr,missense_variant,0.000105
33,96909638,rs138669960,G,A,p.Gly743Asp,missense_variant,0.000138
34,96909661,rs150892504,C,T,p.Arg751Cys,missense_variant,0.003102
35,96912792,rs142362923,T,C,p.Leu837Ser,missense_variant,0.001630
36,96913372,rs780497238,C,G,p.Leu858Val,missense_variant,0.000145
37,96913382,rs145600606,C,T,p.Ala861Val,missense_variant,0.000204
38,96913393,rs201533372,C,T,p.Arg865Cys,missense_variant,0.000145
39,96915765,rs142659150,A,G,p.Gln912Arg,missense_variant,0.000158
40,96917577,rs73152140,T,C,p.Leu952Pro,missense_variant,0.003636

In [8]:
###Adding rsIDs annotation etc by merging GnomAD data####
df1 = ERAP2AlleleFreqPlinkMerge
df2 = ERAP2_gnomeAD
ERAP2_Plink_GnomADmerge = df1.merge(df2, on='POS', how='left')
ERAP2_Plink_GnomADmerge

,POS,REF,ALT,4132678,3856798,1684021,2365580,4866862,5133998,1364128,...,1085546,3156158,4198099,Allele_Freq,rsIDs,Reference,Alternate,Protein_Consequence,VEP_Annotation,Allele Frequency
0,96762462,T,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000608,NaN,NaN,NaN,NaN,NaN,NaN
1,96765121,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000006,NaN,NaN,NaN,NaN,NaN,NaN
2,96765128,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000006,NaN,NaN,NaN,NaN,NaN,NaN
3,96765133,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000009,NaN,NaN,NaN,NaN,NaN,NaN
4,96765137,C,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000015,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,96917665,G,C,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000006,NaN,NaN,NaN,NaN,NaN,NaN
1583,96917682,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000021,NaN,NaN,NaN,NaN,NaN,NaN
1584,96917688,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000015,NaN,NaN,NaN,NaN,NaN,NaN
1585,96917689,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000006,NaN,NaN,NaN,NaN,NaN,NaN
1586,96917703,G,C,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000018,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
####Keeping only Misense variant and splice variant that is just below the exon10 and filtering for MAF >=1/10000####
Exclude = ['synonymous_variant','5_prime_UTR_variant', '3_prime_UTR_variant', 'intron_variant', 'stop_gained', 'frameshift_variant']
ERAP2_Plink_GnomADmerge1 = ERAP2_Plink_GnomADmerge[~ERAP2_Plink_GnomADmerge.VEP_Annotation.isin(Exclude)]
ERAP2_Plink_GnomADmerge2=ERAP2_Plink_GnomADmerge1[ERAP2_Plink_GnomADmerge1.Allele_Freq >= 0.0001]
ERAP2_Plink_GnomADmerge2=ERAP2_Plink_GnomADmerge2.dropna(subset=['VEP_Annotation'])
ERAP2_Plink_GnomADmerge2.loc[ERAP2_Plink_GnomADmerge2['VEP_Annotation'] == 'missense_variant']
ERAP2_Plink_GnomADmerge2

,POS,REF,ALT,4132678,3856798,1684021,2365580,4866862,5133998,1364128,...,1085546,3156158,4198099,Allele_Freq,rsIDs,Reference,Alternate,Protein_Consequence,VEP_Annotation,Allele Frequency
1008,96879799,C,G,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.001090,rs144285538,C,G,p.Phe38Leu,missense_variant,0.000460
1072,96883857,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.001338,rs3733905,C,T,p.Pro214Leu,missense_variant,0.009415
1135,96889200,T,G,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.001126,rs117041256,T,G,p.Ser289Ala,missense_variant,0.010494
1170,96892368,C,T,0|0,0|0,0|0,0|0,0|1,0|0,0|0,...,0|0,0|0,0|0,0.034104,rs75263594,C,T,p.Thr347Met,missense_variant,0.021268
1200,96895296,G,T,1|0,1|1,1|1,1|0,1|1,1|0,0|1,...,1|0,1|0,1|0,0.496985,rs2549782,G,T,p.Lys392Asn,missense_variant,0.541584
1205,96895352,T,G,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.002988,rs34261036,T,G,p.Leu411Arg,missense_variant,0.003390
1223,96896395,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000299,rs148344927,G,A,p.Cys421Tyr,missense_variant,0.000526
1259,96896817,G,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000153,rs201986447,G,A,p.Ser486Asn,missense_variant,0.000217
1283,96900192,A,G,1|0,1|1,1|1,1|0,1|1,1|0,0|1,...,1|0,1|0,1|0,0.497057,rs2248374,A,G,NaN,splice_region_variant,0.541775
1318,96901626,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000755,rs151035607,C,T,p.Arg565Cys,missense_variant,0.000296
1366,96903554,T,A,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|1,0|1,0|0,0.056500,rs17408150,T,A,p.Leu669Gln,missense_variant,0.038022
1399,96909101,T,C,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000799,rs373745801,T,C,p.Ile718Thr,missense_variant,0.000105
1425,96909661,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.001099,rs150892504,C,T,p.Arg751Cys,missense_variant,0.003102
1497,96913382,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000988,rs145600606,C,T,p.Ala861Val,missense_variant,0.000204
1499,96913393,C,T,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000219,rs201533372,C,T,p.Arg865Cys,missense_variant,0.000145
1534,96915765,A,G,0|0,0|0,0|0,0|0,0|0,0|0,0|0,...,0|0,0|0,0|0,0.000308,rs142659150,A,G,p.Gln912Arg,missense_variant,0.000158

In [ ]:
###Save the File for further analysis####
ERAP2_Plink_GnomADmerge2.to_csv('ERAP2_Full_new_March23_final.csv', sep=",", mode='a', index=False)